[package]
name = "pipe-ui"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
default-run = "pipe-ui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "pipe_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
iroh = { version = "1", default-features = false, features = ["tls-ring"] }
iroh-tickets = "1"
url = "2"
http = "1"
bytes = "1"
lazy_static = "1.4"
parking_lot = "0.12"
fastrand = "2"
nexapipe-client = { path = "../../nexapipe/crates/nexapipe-client", features = [
    "local-proxy",
] }


[target.'cfg(windows)'.dependencies]
wintun = "0.5.1"
windows-service = "0.5"

[[bin]]
name = "pipe-service"
path = "src/bin/pipe-service.rs"
